PMSViewerBundle_viewer:
    pattern:  /
    defaults: { _controller: PMSViewerBundle:Viewer:index }

PMSViewerBundle_viewer_sns:
    pattern:  /sns
    defaults: { _controller: PMSViewerBundle:Viewer:sns }

PMSViewerBundle_viewer_server:
    pattern:  /server
    defaults: { _controller: PMSViewerBundle:Viewer:server }

PMSViewerBundle_viewer_account:
    pattern:  /accout
    defaults: { _controller: PMSViewerBundle:Viewer:account }

PMSViewerBundle_viewer_help:
    pattern:  /help
    defaults: { _controller: PMSViewerBundle:Viewer:help }

PMSViewerBundle_viewer_login:
    pattern:  /login
    defaults: { _controller: PMSViewerBundle:Viewer:login }

PMSViewerBundle_viewer_login_check:
    pattern:  /login/check

PMSViewerBundle_viewer_logout:
    pattern:  /logout
