PMSViewerBundle:
    resource: "@PMSViewerBundle/Resources/config/routing.yml"
    prefix:   /

PMSApiBundle:
    resource: "@PMSApiBundle/Resources/config/routing.yml"
    prefix:   /

DeployHtmlBundle:
    resource: "@DeployHtmlBundle/Resources/config/routing.yml"
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
