DeployHtmlBundle:
    resource: "@DeployHtmlBundle/Resources/config/routing.yml"
    prefix:   /

PMSViewerBundle:
    resource: "@PMSViewerBundle/Resources/config/routing.yml"
    prefix:   /viewer

PMSApiBundle:
    resource: "@PMSApiBundle/Resources/config/routing.yml"
    prefix:   /api

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
