security:
  firewalls:
    secured_area:
      form_login: ~
    logout: ~
  providers:
    chain_provider:
      providers: [user_db]
    user_db:
      entity: { class: PMS\ApiBundle\Entity\Account, property: email }
  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: sha1
