# api
PMSApiBundle_api:
    pattern:  /
    defaults: { _controller: PMSApiBundle:Api:index }

PMSApiBundle_api_list:
    pattern:  /list
    defaults: { _controller: PMSApiBundle:Api:list }

# domain
PMSApiBundle_domain_index:
    pattern:  /domain
    defaults: { _controller: PMSApiBundle:Domain:index }

PMSApiBundle_domain_list:
    pattern:  /domain/list
    defaults: { _controller: PMSApiBundle:Domain:list }

PMSApiBundle_domain_add:
    pattern:  /domain/add
    defaults: { _controller: PMSApiBundle:Domain:add }

PMSApiBundle_domain_available:
    pattern:  /domain/available
    defaults: { _controller: PMSApiBundle:Domain:available }

PMSApiBundle_domain_delete:
    pattern:  /domain/delete
    defaults: { _controller: PMSApiBundle:Domain:delete }


# server
PMSApiBundle_server_index:
    pattern:  /server
    defaults: { _controller: PMSApiBundle:Server:index }

PMSApiBundle_server_list:
    pattern:  /server/list
    defaults: { _controller: PMSApiBundle:Server:list }

PMSApiBundle_server_ping:
    pattern:  /server/ping
    defaults: { _controller: PMSApiBundle:Server:ping }

PMSApiBundle_server_add:
    pattern:  /server/add
    defaults: { _controller: PMSApiBundle:Server:add }

PMSApiBundle_server_detail:
    pattern:  /server/detail
    defaults: { _controller: PMSApiBundle:Server:detail }

PMSApiBundle_server_update:
    pattern:  /server/update
    defaults: { _controller: PMSApiBundle:Server:update }

# sns
PMSApiBundle_sns_index:
    pattern:  /sns
    defaults: { _controller: PMSApiBundle:Sns:index }

PMSApiBundle_sns_list:
    pattern:  /sns/list
    defaults: { _controller: PMSApiBundle:Sns:list }

PMSApiBundle_sns_apply:
    pattern:  /sns/apply
    defaults: { _controller: PMSApiBundle:Sns:apply }

PMSApiBundle_sns_detail:
    pattern:  /sns/detail
    defaults: { _controller: PMSApiBundle:Sns:detail }
    
PMSApiBundle_sns_setpass:
    pattern:  /sns/setpass
    defaults: { _controller: PMSApiBundle:Sns:setpass }

PMSApiBundle_sns_delete:
    pattern:  /sns/delete
    defaults: { _controller: PMSApiBundle:Sns:delete }


# sns
PMSApiBundle_account_index:
    pattern:  /account
    defaults: { _controller: PMSApiBundle:Account:index }

PMSApiBundle_account_list:
    pattern:  /account/list
    defaults: { _controller: PMSApiBundle:Account:list }
