parameters:
    pms_api.domain.class: PMS\ApiBundle\Controller\DomainController
    pms_api.server.class: PMS\ApiBundle\Controller\ServerController
    pms_api.sns.class: PMS\ApiBundle\Controller\SnsController
    pms_api.mailer.class: PMS\ApiBundle\Lib\Mailer
    pms_api.listener.request.class: PMS\ApiBundle\Controller\Listener\RequestListener
    mailer_parameter:
        confirmation.template: 'PMSApiBundle:Mail:email.txt.twig'
        from_email:
            confirmation:      'noreply@pne.jp'

services:
    pms_api.domain:
        class: %pms_api.domain.class%
        calls:
            - [setContainer, [@service_container] ]
    pms_api.server:
        class: %pms_api.server.class%
        calls:
            - [setContainer, [@service_container] ]
    pms_api.sns:
        class: %pms_api.sns.class%
        calls:
            - [setContainer, [@service_container] ]
    pms_api.mailer:
        class: %pms_api.mailer.class%
        arguments: [@mailer, @templating, %mailer_parameter%]
    pma_api.listener.request:
        class : %pms_api.listener.request.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
